<a href="https://colab.research.google.com/github/KhusbuBubna123/Reposity1/blob/main/TwitterSentimentAnalysis_Bernoulli_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import string
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report,recall_score,f1_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#df= pd.read_csv("TDataset.csv",sep=',',names=['Sentiment','Tweet_ID','Date','Flag','User','Tweet'],encoding='latin-1',engine="python")
#df.head(8)

df= pd.read_csv("Twitter_Dataset_Binary.csv",sep=',',names=['Sentiment','Tweet_ID','Date','Flag','User','Tweet'],encoding='latin-1')
df.head(8)

#(0 = negative, 4 = positive)

,Sentiment,Tweet_ID,Date,Flag,User,Tweet
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
5,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
6,0,1467811592,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,mybirch,Need a hug
7,0,1467811594,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,coZZ,@LOLTrish hey long time no see! Yes.. Rains a...

In [3]:
df.tail()

,Sentiment,Tweet_ID,Date,Flag,User,Tweet
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [4]:
df.shape

(1600000, 6)

In [5]:
df.columns

Index(['Sentiment', 'Tweet_ID', 'Date', 'Flag', 'User', 'Tweet'], dtype='object')

In [ ]:
#pd.set_option('display.max_rows', None) #Display all the rows.

#Exporatory Data Anlysis.

In [6]:
df['Sentiment'].value_counts() #(0 = negative, 4 = positive)

Sentiment
0    800000
4    800000
Name: count, dtype: int64

In [7]:
df.loc[df['Sentiment'] == 0] #Negative Sentiments

,Sentiment,Tweet_ID,Date,Flag,User,Tweet
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
799995,0,2329205009,Thu Jun 25 10:28:28 PDT 2009,NO_QUERY,dandykim,Sick Spending my day laying in bed listening ...
799996,0,2329205038,Thu Jun 25 10:28:28 PDT 2009,NO_QUERY,bigenya,Gmail is down?
799997,0,2329205473,Thu Jun 25 10:28:30 PDT 2009,NO_QUERY,LeeLHoke,rest in peace Farrah! So sad
799998,0,2329205574,Thu Jun 25 10:28:30 PDT 2009,NO_QUERY,davidlmulder,@Eric_Urbane Sounds like a rival is flagging y...
799999,0,2329205794,Thu Jun 25 10:28:31 PDT 2009,NO_QUERY,tpchandler,has to resit exams over summer... wishes he w...

In [8]:
df.loc[df['Sentiment'] == 4] #Positive Sentiments
#(0 = negative, 4 = positive)

,Sentiment,Tweet_ID,Date,Flag,User,Tweet
800000,4,1467822272,Mon Apr 06 22:22:45 PDT 2009,NO_QUERY,ersle,I LOVE @Health4UandPets u guys r the best!!
800001,4,1467822273,Mon Apr 06 22:22:45 PDT 2009,NO_QUERY,becca210,im meeting up with one of my besties tonight! ...
800002,4,1467822283,Mon Apr 06 22:22:46 PDT 2009,NO_QUERY,Wingman29,"@DaRealSunisaKim Thanks for the Twitter add, S..."
800003,4,1467822287,Mon Apr 06 22:22:46 PDT 2009,NO_QUERY,katarinka,Being sick can be really cheap when it hurts t...
800004,4,1467822293,Mon Apr 06 22:22:46 PDT 2009,NO_QUERY,_EmilyYoung,@LovesBrooklyn2 he has that effect on everyone
...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [4]:
# Tweet length feature

df['Tweet_Length'] = df['Tweet'].apply(len)
df.head()

,Sentiment,Tweet_ID,Date,Flag,User,Tweet,Tweet_Length
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",115
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,111
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,89
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,47
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",111

In [10]:
# Longest Tweet.
max_length=df['Tweet_Length'].max()
df.loc[df['Tweet_Length'] == max_length, 'Tweet'].values[0]

'@catfish_ohm à¹\x80à¸\x84à¹\x89à¸²à¹\x83à¸«à¹\x89à¸?à¸²à¸£à¹\x8cà¸\x95à¸¹à¸\x99à¸?à¸¸à¹\x82à¸£à¸°(à¸ªà¸±à¸ªà¹\x86+à¸¢à¸¹à¸£à¸´à¹?à¸?à¹\x84à¸\x94à¹\x89à¹?à¸\x97à¸\x99à¸\x99à¸°à¸\x9eà¸\xadà¸\x94à¸µà¸¡à¸´à¹\x82à¸?à¸°à¸«à¸§à¸\x87(à¸\x82à¸\x99à¸²à¸\x94à¹\x80à¸\x9fà¸´à¸\x99à¹?à¸?à¸¢à¸±à¸\x87à¹\x80à¸\x84à¸¢à¹\x83à¸«à¹\x89à¹\x84à¸¡à¹\x88à¹\x83à¸\x8aà¹\x88à¹\x80à¸«à¸£à¸\xad.à¹?à¸\x95à¹\x88à¸\x8aà¹\x88à¸²à¸\x87à¹\x80à¸«à¸\xadà¸°à¸£à¸²à¸¢à¸\x99à¸±à¹\x89à¸\x99à¹\x80à¸\x82à¸²à¹\x82à¸¡à¹\x80à¸\xadà¸°à¸?à¸§à¹\x88à¸²à¸\x9bà¸¥à¸²à¹?à¸¡à¸§à¹\x80à¸¢à¸\xadà¸° = '

In [11]:
print("Length of Longest Tweet",max_length)

Length of Longest Tweet 374

In [12]:
# Shortest Tweet
min_length=df['Tweet_Length'].min()
df.loc[df['Tweet_Length'] == min_length, 'Tweet'].values[0]

' just '

In [13]:
print("Length of Shortest Tweet",df['Tweet_Length'].min())

Length of Shortest Tweet 6

#Text Preprocessing.

#Removing punctuation and converting to lower case.

In [14]:
def remove_punct(text):
    return ''.join(ch for ch in text if ch not in string.punctuation)

def convert_lower(text):
    return text.lower()

df['Tweet_clean'] = df['Tweet'].apply(remove_punct)
df['Tweet_clean'] = df['Tweet_clean'].apply(convert_lower)
df.head(8)

,Sentiment,Tweet_ID,Date,Flag,User,Tweet,Tweet_Length,Tweet_clean
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",115,switchfoot httptwitpiccom2y1zl awww thats a b...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,111,is upset that he cant update his facebook by t...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,89,kenichan i dived many times for the ball manag...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,47,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",111,nationwideclass no its not behaving at all im ...
5,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,29,kwesidei not the whole crew
6,0,1467811592,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,mybirch,Need a hug,11,need a hug
7,0,1467811594,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,coZZ,@LOLTrish hey long time no see! Yes.. Rains a...,99,loltrish hey long time no see yes rains a bit...

#Splitting into Train and Test Data

In [15]:
X = df['Tweet_clean'].values
Y = df['Sentiment'].values.astype(int)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=10)

print('Train size:', len(X_train))
print('Test  size:', len(X_test))

Train size: 1280000
Test  size: 320000

#Vectorisation — Bag of Words (CountVectorizer)

In [34]:
#Count Vectorize and remove stopwords.
CV = CountVectorizer(stop_words='english')
X_train_cv = CV.fit_transform(X_train)
X_test_cv  = CV.transform(X_test)

print('Vocabulary size:', len(CV.vocabulary_))
print('Train shape    :', X_train_cv.shape)
print('Test  shape    :', X_test_cv.shape)

Vocabulary size: 720874
Train shape    : (1280000, 720874)
Test  shape    : (320000, 720874)

In [35]:
feature_names = CV.get_feature_names_out()
print('Total features:', len(feature_names))
print('Sample feature tokens  :', feature_names[:100]) #Printing First 100 tokens from the Vocaborary.

Total features: 720874
Sample feature tokens  : ['00' '000' '0000' '00000' '0000000000' '00000001' '0000001' '0000014'
 '000009260gbs' '0000abcd' '0000ff' '0001' '0001110101001010000111'
 '0001am' '0001t' '0002' '0003' '0005' '00055' '00055gbmin' '0005am'
 '0005mm' '0007' '0009' '000aah' '000h' '000martha' '000month' '000quot'
 '000s' '000webhost' '001' '0010' '0010utc' '0010x0010'
 '0011000100101011001100010011110100110010' '0012' '0014' '0019' '001quot'
 '001sec' '002' '0020' '00202' '002345' '0029' '003' '0030' '0031' '0035'
 '0036' '003r' '003ï' '004' '0045' '0047' '0049' '005' '0050' '0051'
 '0054am' '0055gb60sec' '005603' '0058' '006' '0069' '007' '00711' '0074'
 '007episode' '007heather007' '007hil' '007jbond' '007peter' '007wisdom'
 '008' '0084' '00ff00' '00fieldsy' '00g' '00geneva' '00jon' '00k'
 '00mathias' '00mony00' '00neji' '00pet00' '00pmpray' '00poloshawty'
 '00ps' '00s' '00seve' '00vicky00' '00where' '01' '010' '0100' '01000'
 '01000101' '0106']

#Training the model — Bernoulli Naive Bayes

In [77]:
NB = BernoulliNB(alpha=0.01) #alpha is used for Laplace smooothing.
NB.fit(X_train_cv, Y_train)
Y_Predict = NB.predict(X_test_cv)
Y_Predict

array([0, 0, 4, ..., 0, 0, 4])

In [78]:
#y_predict=y_predict.replace({0:"beningn",1:"Malignant"})
y_cat_variable = pd.Categorical(Y_Predict).rename_categories({0:"Negative Sentiment", 4:"Positive Sentiment"})
y_cat_variable

#(0 = negative, 4 = positive)

['Negative Sentiment', 'Negative Sentiment', 'Positive Sentiment', 'Negative Sentiment', 'Positive Sentiment', ..., 'Positive Sentiment', 'Negative Sentiment', 'Negative Sentiment', 'Negative Sentiment', 'Positive Sentiment']
Length: 320000
Categories (2, object): ['Negative Sentiment', 'Positive Sentiment']

#Accuracy

In [79]:
print(f'Bernoulli Naive Bayes Accuracy using Count Vectorizer: {accuracy_score(Y_test, Y_Predict)*100:.2f}%')

Bernoulli Naive Bayes Accuracy using Count Vectorizer: 74.89%

#F1 score

In [83]:
f1_score=f1_score(Y_Predict,Y_test,pos_label=4)
f1_score

0.7451837102235976

In [82]:
recall=recall_score(Y_Predict,Y_test,pos_label=4)
recall

0.7570463140127429

In [84]:
print(classification_report(Y_test, Y_Predict, target_names=['Positive Sentiment', 'Negative Sentiment']))

                    precision    recall  f1-score   support

Positive Sentiment       0.74      0.76      0.75    159835
Negative Sentiment       0.76      0.73      0.75    160165

          accuracy                           0.75    320000
         macro avg       0.75      0.75      0.75    320000
      weighted avg       0.75      0.75      0.75    320000

#Printing Confusion Matrix.

In [85]:
cm = pd.DataFrame(
    confusion_matrix(Y_test, Y_Predict),
    index=['Actual Positive', 'Actual Negative'],
    columns=['Predicted Positive', 'Predicted Negative'],
)
cm

                 Predicted Positive  Predicted Negative
Actual Positive              122123               37712
Actual Negative               42654              117511

#Testing on a New Tweet.

In [3]:
def classify_tweet(tweet):
    cleaned  = remove_punct(tweet)
    cleaned = convert_lower(cleaned)
    features = CV.transform([cleaned])
    Predict = NB.predict(features)[0]
    if(Predict == 0):
      Sentiment='Negative Sentiment'
    elif(Predict== 4):
      Sentiment='Positive Sentiment'
    return Sentiment
#(0 = negative, 4 = positive)

In [96]:
#Neutral Sentiment Tweet.
Tweet1='this comes from cabinet which has scholars like modi smriti and hema time introspect'

In [97]:
sentiment=classify_tweet(Tweet1)
print(sentiment)

Positive Sentiment

In [110]:
Tweet2='talk all the nonsense and continue all the drama will vote for modi'

In [111]:
sentiment=classify_tweet(Tweet2)
print(sentiment)

Positive Sentiment

In [112]:
#Neutral Sentiement.
Tweet2="one vote can make all the difference anil kapoor answers modis election 2019 clarion call extends support his vote kar campaign"

In [113]:
sentiment=classify_tweet(Tweet2)
print(sentiment)

Positive Sentiment

In [108]:
Tweet3="with firm belief the leadership shri narendra modi bjp entering into politics given form file nomination for the khammam parliamentary seat proceeding khammam today"
#negative Tweet Sentiment.

In [109]:
sentiment=classify_tweet(Tweet3)
print(sentiment)

Positive Sentiment

In [104]:
Tweet4="	hope tuthukudi people would prefer honest well behaved nationalist courageous likly minister modi cabinet vote benifit thuthukudi"
#Positive Tweet Sentiment

In [105]:
sentiment=classify_tweet(Tweet4)
print(sentiment)

Negative Sentiment

In [106]:
#Positive Sentiment Tweet.
Tweet5='answer who among these the most powerful world leader today trump putin modi may'

In [107]:
sentiment=classify_tweet(Tweet5)
print(sentiment)

Positive Sentiment

#Vectorisation —TF-IDF Vectorization.

In [5]:
tf = TfidfVectorizer()

X_train_tf = tf.fit_transform(X_train[:100]).toarray()
X_test_tf  = tf.transform(X_test).toarray()

# FIX 4: get_feature_names_out() replaces deprecated get_feature_names()
print('TF-IDF features:', len(tf.get_feature_names_out()))
print('Train shape     :', X_train_tf.shape)
print('Test  shape     :', X_test_tf.shape)

NameError: name 'X_train' is not defined

In [17]:
NB = BernoulliNB(alpha=0.01) #alpha is used for Laplace smooothing.
NB.fit(X_train_tf, Y_train)

ValueError: Found input variables with inconsistent numbers of samples: [100, 1280000]

In [ ]:
Y_Predict = NB.predict(X_test_tf)
Y_Predict

In [ ]:
accuracy = accuracy_score(Y_test, Y_Predict) * 100
print(f'MultinomialNB Accuracy: {accuracy:.2f}%')

In [ ]:
f1_score=f1_score(Y_Predict,Y_test,pos_label=4)
f1_score

In [ ]:
recall=recall_score(Y_Predict,Y_test,pos_label=4)
recall

In [ ]:
print(classification_report(Y_test, Y_Predict, target_names=['Positive Sentiment', 'Negative Sentiment']))

In [ ]:
cm = pd.DataFrame(
    confusion_matrix(Y_test, Y_Predict),
    index=['Actual Positive', 'Actual Negative'],
    columns=['Predicted Positive', 'Predicted Negative'],
)
cm

                 Predicted Positive  Predicted Negative
Actual Positive              122123               37712
Actual Negative               42654              117511

#Testing on a New Tweet.

In [ ]:
def classify_tweet(tweet):
    cleaned  = remove_punct(tweet)
    cleaned = convert_lower(cleaned)
    features = CV.transform([cleaned])
    Predict = NB.predict(features)[0]
    if(Predict == '0'):
      Sentiment='Negative Sentiment'
    elif(Predict=='4'):
      Sentiment="Positive Sentiment"
    return Sentiment
#(0 = negative, 4 = positive)

In [ ]:
#Neutral Sentiment Tweet.
Tweet1='this comes from cabinet which has scholars like modi smriti and hema time introspect'

In [ ]:
sentiment=classify_tweet(Tweet1)
print(sentiment)

In [ ]:
#Neutral Sentiement.
Tweet2="one vote can make all the difference anil kapoor answers modis election 2019 clarion call extends support his vote kar campaign"

In [ ]:
sentiment=classify_tweet(Tweet2)
print(sentiment)

In [ ]:
Tweet3="with firm belief the leadership shri narendra modi bjp entering into politics given form file nomination for the khammam parliamentary seat proceeding khammam today"
#negative Tweet Sentiment.

In [ ]:
sentiment=classify_tweet(Tweet3)
print(sentiment)

In [ ]:
Tweet4="	hope tuthukudi people would prefer honest well behaved nationalist courageous likly minister modi cabinet vote benifit thuthukudi"
#Positive Tweet Sentiment

In [ ]:
sentiment=classify_tweet(Tweet4)
print(sentiment)

In [ ]:
#Positive Sentiment Tweet.
Tweet5='answer who among these the most powerful world leader today trump putin modi may'

In [ ]:
sentiment=classify_tweet(Tweet5)
print(sentiment)